### ISSUE TITLE
BOOST

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#4]
BOOST should not be required for compilation of Gpufit.

**Comment by jkfindeisen** [comment]
I think it isn't. Cmake outputs a warning but the library can be compiled. The tests will be missing. Since a frame like BOOST-TEST helps considerably with automatic testing I recommend to continue requiring it for the tests. Probably we should:

- Modify the cmake scripts so that a more meaningful message is written (no boost, no tests)
- Add information about this to the documentation (boost required for executing the tests)

**Comment by bjoernthiel** [comment]
build prerequisites and CMake message added
