### ISSUE TITLE
Add a new fit model+ MATLAB

### ISSUE THREAD

**Issue by ehna** [gpufit/Gpufit#41]
I did add a new fit model according to the instruction, but it did not show up in the list of ModelID.m. I noticed I have to add my model to ModelID.m in C:\Sources\Gpufit-master\Gpufit\matlab folder.

**Comment by jkfindeisen** [comment]
In order to use the fit model from Matlab just use it's number as ID. The ModelID.m ist just a convenience method to provide names for the numbers. It's independent from Gpufit and not automatically generated. This means:

- Either just use the ID number of your model as model ID.
- Or modify ModelID.m to get the same style as the examples.

We might want to be a bit more clear about that in the documentation.

**Comment by superchromix** [comment]
Agreed that we should update the documentation to include this detail, that modelID.m should be modified when adding a new model function.
