### ISSUE TITLE
Inconsistent capitalization e.g. CPUfit, CpuFit, GPUfit, GpuFit

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#55]
Please remove all capitalization of CPUFIT and GPUFIT

new style:
cpufit
gpufit

does this remind you of the 1970s?  get over it.

**Comment by superchromix** [comment]
note, this issue refers only to the CODE.

in the docs, etc, it is fine to use GPUfit, GpuFit, as you wish.  I prefer GPUfit.

**Comment by bjoernthiel** [comment]
According to http://www.stroustrup.com/JSF-AV-rules.pdf I suggest gpu_fit and Gpu_Fit.

**Comment by jkfindeisen** [comment]
I think gpufit and cpufit are better choices than gpu_fit or cpu_fit because then we have a single prefix for many functions. One could probably see gpufit as a single word.

As for the wording of the toolbox in the paper, I thought we had agreed on GPUfit which is reasonable by itself (GPU being an acronym). However I would be fine with Gpufit too. But I think it should be only one of them, not as you wish.

**Comment by superchromix** [comment]
I prefer cpufit and gpufit for the code.  It is maddening trying to use these matlab functions and having to guess which capitalization to use.

In the paper and docs, CPUfit and GPUfit makes sense.

**Comment by adrianjp88** [comment]
I agree with gpufit/cpufit and GPUfit/CPUfit
