### ISSUE TITLE
the python version of gpufit should be named "pyGpufit"

### ISSUE THREAD

**Issue by superchromix** [gpufit/GPUfit#72]

**Comment by superchromix** [comment]
bearing in mind that there is already a package called "PyGPU"

**Comment by jkfindeisen** [comment]
I don't think it should. Python library names are mostly lowercase, almost never camel case. The py prefix or sufix is rather seldomly used. Just see http://www.lfd.uci.edu/~gohlke/pythonlibs/ or https://pypi.python.org/pypi?%3Aaction=search&term=gpu&submit=search for examples.

Possible namings:

- gpufit
- pygpufit
- gpufitpy
- pyGPUfit
- GPUfitpy

My vote goes either to pyGPUfit or to gpufit, because everything else doesn't look and the pyGpufit looks even worse and doesn't comply with the capitalization rules we defined in #55.

**Comment by bjoernthiel** [comment]
we should follow [PEP 8](https://www.python.org/dev/peps/pep-0008/#package-and-module-names)

**Comment by adrianjp88** [comment]
I think gpufit is the best choice

**Comment by jkfindeisen** [comment]
For the module I prefer gpufit and it is already like this. It's all underscore as requested by PEP 8 and it is without the py prefix because I don't feel it's necessary or adds anything about when coding it except length.

The name of the Python binding however, i.e. the package name on PyPi can be different. In the name of consistency within the project we might want to call it gpufit, GPUfit or even pyGPUfit or something different. Package and module names do not have to be the same.

**Comment by superchromix** [comment]
great.  I support pyGPUfit.

**Comment by jkfindeisen** [comment]
fine, then gpufit it is for the module name and pyGPUfit for the package.
