### ISSUE TITLE
Do I have to provide analytic expressions of partial derivatives for customized model function?

### ISSUE THREAD

**Issue by dejavumono** [gpufit/Gpufit#86]
In the [documentation,](https://gpufit.readthedocs.io/en/latest/customization.html) it says "To add a new fit model, the model function itself as well as **analytic expressions for its partial derivatives must to be known**."  I have a model based on simulation, i.e. it does not have an analytical form. Can I calculate the derivatives numerically? 

My problem can be descitbed as follows,
`y=simulation(x, p0, p1, p2, p3, p4)`
where x, y are data samples, and p0,p1,p2,p3,p4 are model parameters I try to fit. They are all scalars.

**Comment by superchromix** [comment]
If you need to run a simulation in order to calculate the function value, for a given set of model parameters, this sounds like the type of computation that would be difficult to do within the GPU threads.  Moreover, the simulation would need to be re-run many times in order to generate approximate values for the derivatives.

Gpufit does not include any built-in functionality for numerical estimation of the derivatives.  It might not be the best optimizer for your problem, therefore.

If you can somehow run the simulation within the model function itself, and also estimate the derivatives numerically, this in principle could work but I anticipate it would be agonizingly slow, and could cause problems with thread calculations taking too long to complete and timing out.

**Comment by dejavumono** [comment]
The model function and derivatives are easy to implement. As for the speed, I have no idea, I'll create a demo to evaluate whether GPU can give any speedup first.
